### PR TITLE
Ruby 2.5 support

### PR DESCRIPTION
**Pull request by schm**
* Update CI rubies
* Support `warn` with `uplevel`

### CODE REVIEW

**Comment by dewey4iv** [comment]
Hello, are there any technical reasons for not merging this? Currently, we are running Ruby 2.6.3 are unable to use this gem.

**Comment by tyler-ball** [comment]
Howdy! We're also facing this bug in our usage of structured warnings, and this PR fixes it. Is there anything I can do to help get this merged and released?

**Comment by schmidt** [comment]
Sorry for the long delay. The PR wasn't properly tested for full compatibility yet. I just covered the basic: "What needs to happen to make the error go away".

I was hoping to perform more detailed tests about this new feature and how it's supposed to work. But then I didn't find the time to get back to it.

If this branch works fine for you, feel free to keep using it.  👍

**Comment by schmidt** [comment]
Directly pushed to master and released in v0.4.0. Thank you for your patience.

**Comment by tyler-ball** [comment]
Thank you @schmidt !

**Pull request closed without merging**
